# Generated by Django 4.2.7 on 2024-01-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
